repos:
  - repo: local
    hooks:
      - id: yapf
        name: yapf
        language: python
        entry: yapf
        args: [-i, -vv, --style, .style.yapf]
        files: \.pyi?$
        additional_dependencies:
          - yapf

      - id: flake8
        name: flake8
        entry: flake8
        args: [--config, .flake8]
        language: python
        files: \.pyi?$
        additional_dependencies:
          - flake8

default_install_hook_types: [pre-commit, pre-push, pre-merge-commit]
